# Yaml ilustrative to knowledge
# Your yaml needs information from actual yaml file
# This manifest will be merged with the current to generate the correct one
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, syncuser, applications, sync, default/*, allow